In [5]:
#Linear regression with multiple variables

#Handling NA values
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv(r"F:\py-master\ML\2_linear_reg_multivariate\homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
#Data preprocessing
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
reg = linear_model.LinearRegression()
#fit method is used to train the model
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540443

In [ ]:
#price = m1 * area + m2 * bedrooms + m3 * age + b

#m1,m2,m3 are co-efficients and b is intercept

In [ ]:
#Given these home prices find out price of a home that has

3000 sqrft area,3 bedrooms, 40 year old

2500 sqrft area,4 bedrooms, 5 year old

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [13]:
reg.predict([[2500,4,5]])

array([578876.03748933])